window.mathJokes = [
    "Why did the math book look sad? Because it had too many problems.",
    "Why do mathematicians like parks? Because of all the natural logs.",
    "Why was the equal sign so humble? It knew it was not greater than or less than anyone else.",
    "I told my math teacher I would never use algebra in real life. Then I needed to find x.",
    "Parallel lines have so much in common. It is a shame they will never meet.",
    "What is a mathematician's favorite place in NYC? Times Square.",
    "Why did the triangle go to therapy? It had too many unresolved angles.",
    "Why was the fraction nervous about marriage? It was afraid to commit.",
    "Why did the student eat his homework? The teacher said it was a piece of pi.",
    "Why did the circle go to school? To improve its circumference.",
    "What do you call a number that cannot keep still? A roamin' numeral.",
    "Why did the two fours skip lunch? They already eight.",
    "What is the integral of 1 over cabin? A natural log cabin.",
    "Why do mathematicians dislike the U.S.? Because it is indivisible.",
    "Why did the statistician bring a ladder? To reach a higher mean.",
    "Why was the geometry lecture so long? The professor kept going off on tangents.",
    "Why did the decimal get promoted? It was outstanding in its field.",
    "What did the sine say to the cosine? We make a great pair.",
    "Why was the angle upset? It was feeling a little obtuse.",
    "Why do robots love math? It helps them stay well calculated.",
    "What did zero say to eight? Nice belt.",
    "Why did the mathematician break up with the calculator? It was too dependent.",
    "Why did the function stop using social media? It was tired of being undefined.",
    "Why did the graph paper blush? It saw the slope.",
    "What do you get when you cross a math teacher and a clock? Arithme-ticks.",
    "Why did the prime number refuse to share? It could only be divided by itself and one.",
    "Why did the polynomial apply for a job? It wanted a higher degree.",
    "Why was the compass feeling confident? It knew its bearings.",
    "Why did the matrix go to the party? It had the right dimensions.",
    "Why was the parabola always invited? It knew how to make a great arc.",
    "Why did the exponent break up? It felt too power hungry.",
    "Why was the math lecture so cool? It had a lot of radians.",
    "Why did the number line get a haircut? It needed a straight edge.",
    "Why did the angle go to the beach? It wanted to get a tan-gent.",
    "Why did the set stay calm? It had no worries in its union.",
    "Why did the derivative win the race? It was quick on the slope.",
    "Why did the coordinate plane get invited? It always brought good points.",
    "Why did the log file feel important? It had a strong base.",
    "Why did the graph go to the gym? To work on its axes.",
    "Why did the integer blush? It saw a point.",
    "Why did the calculator go to the party? It was ready to add to the fun.",
    "Why was the limit so patient? It knew how to approach problems.",
    "Why did the vector feel directed? It had both magnitude and purpose.",
    "Why did the proof feel proud? It had a solid argument.",
    "Why did the sequence stay organized? It had a clear order.",
    "Why did the mathematician carry a pencil? To draw conclusions.",
    "Why was the equation calm? It already balanced everything out.",
    "Why did the teacher love circles? They were well-rounded.",
    "Why did the area of a circle want attention? It was feeling pi-rated.",
    "Why did the sum get invited twice? It was a total hit.",
    "Why did the inequality sign feel left out? It was not equal to the others.",
    "Why was the hypotenuse so relaxed? It was just the longest side.",
    "Why did the math student bring a ladder to class? To reach the high scores.",
    "Why did the sequence go to therapy? It had recursion issues.",
    "Why did the calculator stay home? It could not compute the weather.",
    "Why did the number 6 hate the number 7? Because 7 8 9.",
    "Why did the angle get a promotion? It was right for the job.",
    "Why did the graph look so confident? It had strong points.",
    "Why did the measure teacher smile? It had good degrees.",
    "Why did the function get invited to dinner? It was well-behaved at the table.",
    "Why did the fraction go to the gym? To get reduced.",
    "Why did the algebra book look tired? It had too many x's to deal with.",
    "Why did the geometry student bring string? To measure the arc.",
    "Why did the polygon get praise? It had many sides to its story.",
    "Why did the dot product stay quiet? It did not want to be cross.",
    "Why did the proof walk into the bar? To show it could be proven.",
    "Why did the sine wave feel smooth? It had good vibes.",
    "Why did the cosine wave feel shy? It kept to itself.",
    "Why was the set so inclusive? It had a generous union.",
    "Why did the mathematician love coffee? It helped with continuous work.",
    "Why did the graphing calculator smile? It saw the big picture.",
    "Why was the coordinate plane calm? It had good balance.",
    "Why did the function go hiking? It wanted a change of domain.",
    "Why did the numerator brag? It was on top.",
    "Why did the denominator stay grounded? It kept things in check.",
    "Why did the mathematician like music? It had great rhythms and measures.",
    "Why did the angle feel sharp? It was acute.",
    "Why did the function go to the party? It had a constant plus one.",
    "Why did the sequence go on vacation? It needed a break in the series.",
    "Why did the graph go to art class? It wanted better curves.",
    "Why did the proof get applause? It was well-constructed.",
    "Why did the number line feel positive? It had good points.",
    "Why did the parabola feel confident? It had a strong focus.",
    "Why did the circle feel complete? It had no loose ends.",
    "Why did the vector look determined? It had direction.",
    "Why did the mathematician love winter? It had nice slopes.",
    "Why did the calculus student smile? It all came together.",
    "Why did the mean stay calm? It always averaged out.",
    "Why did the median feel centered? It was right in the middle.",
    "Why did the mode feel popular? It showed up the most.",
    "Why did the variable bring a suitcase? It was ready to change.",
    "Why did the line go to the party? It knew the right angle.",
    "Why did the matrix get invited? It had a great arrangement.",
    "Why did the series feel special? It knew how to converge.",
    "Why did the circle join the band? It had great rhythm.",
    "Why did the mathematician like gardening? It had good roots.",
    "Why did the function feel confident? It was well-defined.",
    "Why did the graph feel proud? It had a good slope.",
    "Why did the triangle feel strong? It had a solid base.",
    "Why did the exponent smile? It had power.",
    "Why did the number feel safe? It was in good bounds.",
    "Why did the integral stay calm? It had boundaries.",
    "Why did the coordinate plane feel square? It had right angles.",
    "Why did the math student bring snacks? For the pi break.",
    "Why did the theorem feel secure? It was well-proved.",
    "Why did the circle feel classic? It was timeless.",
    "Why did the proof feel certain? It had no gaps.",
    "Why did the tangent feel excited? It got to touch the curve.",
    "Why did the derivative feel energetic? It was always changing.",
    "Why did the limit feel close? It could approach anything.",
    "Why did the ratio feel balanced? It was in proportion.",
    "Why did the integer feel whole? It had no parts.",
    "Why did the prime feel unique? It stood alone.",
    "Why did the slope feel confident? It knew its rise and run.",
    "Why did the sequence feel tidy? It had a pattern.",
    "Why did the math club stay late? It was solving problems.",
    "Why did the variable feel flexible? It could be anything.",
    "Why did the fraction feel small? It was just a piece.",
    "Why did the equation smile? It was balanced.",
    "Why did the circle get hired? It was well-rounded.",
    "Why did the parabolic arc feel bold? It had a strong curve.",
    "Why did the number line feel long? It went on forever.",
    "Why did the proof feel elegant? It was concise.",
    "Why did the mathematician stay calm? It was all rational.",
    "Why did the graph feel stable? It was well-scaled.",
    "Why did the angle feel right? It was exactly 90 degrees.",
    "Why did the limit feel patient? It could wait forever.",
    "Why did the vector feel strong? It had magnitude.",
    "Why did the axis feel important? It kept everything aligned.",
    "Why did the function smile? It had a domain and range.",
    "Why did the sine wave feel steady? It had good oscillations.",
    "Why did the cosine wave feel consistent? It kept its phase.",
    "Why did the tangent feel bold? It touched without crossing.",
    "Why did the statistics student smile? The data told a story.",
    "Why did the number zero feel chill? It had no worries.",
    "Why did the variable feel curious? It wanted to solve itself.",
    "Why did the graph feel happy? It had positive values.",
    "Why did the calculator laugh? It had a good sum.",
    "Why did the math student relax? It was all in the solution.",
    "Why did the root feel grounded? It was well-based.",
    "Why did the base feel steady? It supported everything.",
    "Why did the integral feel complete? It accounted for everything.",
    "Why did the sum feel proud? It added up.",
    "Why did the math class smile? It was well-structured.",
    "Why did the proof feel done? It reached QED.",
    "Why did the equation feel settled? It had balance.",
    "Why did the curve feel smooth? It had no corners.",
    "Why did the coordinate plane feel organized? It had good axes.",
    "Why did the fraction feel steady? It was reduced.",
    "Why did the graph feel clear? It was well-labeled.",
    "Why did the angle feel confident? It was acute.",
    "Why did the number feel lucky? It was prime.",
    "Why did the function feel open? It had no restrictions.",
    "Why did the sequence feel relaxed? It converged.",
    "Why did the denominator smile? It held things together.",
    "Why did the numerator grin? It was on top.",
    "Why did the line feel simple? It had a straight path.",
    "Why did the matrix feel helpful? It organized data.",
    "Why did the derivative feel quick? It knew the slope.",
    "Why did the parabola feel focused? It had a clear point.",
    "Why did the math joke feel safe? It was clean and easy to compute.",
    "Why did the math student smile at lunch? It was time for pi.",
    "Why did the function feel proud? It never went out of range.",
    "Why did the teacher love math? It always added up.",
    "Why did the graph feel artistic? It had great curves.",
    "Why did the tangent line feel special? It touched just once.",
    "Why did the proof feel confident? It was logically sound.",
    "Why did the variable feel open-minded? It could take any value.",
    "Why did the integral feel important? It covered the whole area.",
    "Why did the slope feel steady? It was constant.",
    "Why did the calculator feel calm? It had all the functions.",
    "Why did the equation feel fair? It treated both sides equally.",
    "Why did the math student smile at the end? It all made sense.",
    "Why did the mean feel friendly? It liked to average things out.",
    "Why did the median feel centered? It stayed in the middle.",
    "Why did the mode feel popular? It appeared the most.",
    "Why did the statistics book smile? It had good data.",
    "Why did the graph feel neat? It was well-plotted.",
    "Why did the angle feel sharp? It was acute.",
    "Why did the theorem feel important? It was fundamental.",
    "Why did the base feel proud? It supported the exponent.",
    "Why did the exponent feel powerful? It had extra strength.",
    "Why did the line feel confident? It had a clear direction.",
    "Why did the coordinate feel proud? It had a point.",
    "Why did the math class feel good? It had a positive sum.",
    "Why did the number line feel excited? It had infinite possibilities.",
    "Why did the fraction feel confident? It was simplified.",
    "Why did the equation feel resolved? It had a solution.",
    "Why did the integral feel smooth? It followed the curve.",
    "Why did the proof feel complete? It reached the conclusion.",
    "Why did the graph feel balanced? It had symmetry.",
    "Why did the circle feel complete? It had 360 degrees.",
    "Why did the tangent feel calm? It only touched the curve.",
    "Why did the sine feel happy? It was in phase.",
    "Why did the cosine feel steady? It kept its rhythm.",
    "Why did the vector feel strong? It had direction and magnitude.",
    "Why did the set feel complete? It had all its elements.",
    "Why did the limit feel close? It could approach.",
    "Why did the math student smile? The problem was solved.",
    "Why did the proof feel elegant? It was concise.",
    "Why did the algebra feel friendly? It was easy to solve.",
    "Why did the geometry feel stylish? It had great angles.",
    "Why did the calculus feel powerful? It handled change.",
    "Why did the statistics feel wise? It knew the data.",
    "Why did the graph feel useful? It showed the trend.",
    "Why did the number feel whole? It was complete.",
    "Why did the equation feel stable? It was balanced.",
    "Why did the function feel strong? It was well-defined.",
    "Why did the math teacher smile? The class understood.",
    "Why did the numbers feel happy? They added up.",
    "Why did the calculator feel helpful? It had solutions.",
    "Why did the math student relax? It was all rational.",
    "Why did the formula feel clean? It was simplified.",
    "Why did the function feel smooth? It was continuous.",
    "Why did the limit feel safe? It stayed within bounds.",
    "Why did the angle feel proud? It was right.",
    "Why did the circle feel perfect? It had constant radius.",
    "Why did the number feel confident? It was prime.",
    "Why did the triangle feel strong? It had a solid base.",
    "Why did the sum feel complete? It added up.",
    "Why did the mean feel friendly? It always averaged out.",
    "Why did the median feel calm? It stayed centered.",
    "Why did the mode feel popular? It showed up most.",
    "Why did the variable feel flexible? It could change.",
    "Why did the proof feel done? QED.",
    "Why did the slope feel smooth? It was constant.",
    "Why did the derivative feel sharp? It knew the rate.",
    "Why did the integral feel complete? It captured the area.",
    "Why did the function feel confident? It had no discontinuities.",
    "Why did the math class cheer? The solution was elegant.",
    "Why did the graph feel clear? It was well-scaled.",
    "Why did the mathematician smile? The proof worked.",
    "Why did the equation feel fair? Both sides matched.",
    "Why did the number feel special? It was irrational.",
    "Why did the angle feel happy? It was acute.",
    "Why did the number line feel endless? It went on forever.",
    "Why did the function feel calm? It was continuous.",
    "Why did the triangle feel famous? It had a right angle.",
    "Why did the parabola feel proud? It had a clear focus.",
    "Why did the logarithm feel stable? It had a strong base.",
    "Why did the graph feel proud? It had a good fit.",
    "Why did the mathematician relax? It was all solved.",
    "Why did the number feel safe? It was within bounds.",
    "Why did the set feel friendly? It welcomed all elements.",
    "Why did the equation feel complete? It had a solution.",
    "Why did the function feel special? It was one-to-one.",
    "Why did the slope feel steady? It was linear.",
    "Why did the derivative feel helpful? It showed change.",
    "Why did the integral feel useful? It measured area.",
    "Why did the math student smile? The theorem made sense.",
    "Why did the graph feel accurate? It had good data.",
    "Why did the number feel bold? It was prime.",
    "Why did the proof feel perfect? It was complete.",
    "Why did the function feel simple? It was linear.",
    "Why did the triangle feel balanced? It had equal sides.",
    "Why did the number feel unique? It was prime.",
    "Why did the math class feel confident? The answer checked out.",
    "Why did the equation feel fair? It was balanced.",
    "Why did the math student relax? It was solved.",
    "Why did the proof feel elegant? It was concise.",
    "Why did the number feel proud? It was a perfect square."
];